### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#13]
* [x] Listen to preview plays
* [x] Support a specif to artists
* [x] Browse and find artists `3`
* [x] Buy an album
  * [x] Download a purchased album `3` 
  * [x] Receive a receipt for an album purchase `3` Depends on #24
* [x] Receive posts from an artist via email `3` Depends on #24 and #30 
* [x] See feed of people you subscribe to `1` 
* [x] Receive monthly receipt from subscriptions `3 Depends on #24 
* [x] Cancel a subscription `2`
* [x] View collection of purchased albums
* [x] Listen to collection of purchased albums
