### ISSUE TITLE
Design scales: color

### ISSUE THREAD

**Issue by timglorioso** [funmusicplace/mirlo#130]
### Objective

- Establish a single source of truth for Mirlo design scales
- Establish a single source of truth for tokens, currently spread across CSS custom properties and Emotion theme
- Prepare to facilitate future visual changes by embedding design thinking in the frontend code

### Solution

Consolidate the following styling resources:
- Javascript tokens from `theme.ts`
- CSS tokens and styles from `styles.ts`
- CSS styles from `index.css`

Part of this consolidation involves converting all CSS custom properties to Javascript theme tokens. 

#### Example

```js
// mirloDesignScales.ts
export const color = {
  black: "#3E363F",
  white: "#FFEEDB"
}
```
```js
// theme.ts
import { color } from "./mirloDesignScales"

const dark = {
  background: color.black
}

const light = {
  background: color.white
}
```

### Tasks

- [ ] Establish Mirlo design scales, starting with color
- [ ] Use color scales to populate Emotion themes for dark/light modes
- [ ] Listen for dark/light mode changes from `window.matchMedia`
- [ ] Replace CSS custom properties with Emotion theme tokens
- [ ] TBD...

**Comment by timglorioso** [comment]
@simonv3 I'd appreciate your thoughts on the Solution here, make sure I'm not moving in a wrong direction

**Comment by simonv3** [comment]
@timglorioso sorry I didn't see your question from earlier. Honestly it feels like you have more experience and thoughts on this than I do! I'm happy with whatever you think works best. 

I think you're right in that consolidating things into one spot is the right move. I was moving towards using `var(--mi-variable)` but if you think it's best to use themes than that works. 

I think the main thing to flag and keep in mind as it gets designed (and I think you are minding it!) is the desire to ultimately let musicians define their own page styles. How I was envisioning solving that with the `var(--mi-variable)` stuff was basically to just inject a style on artist pages that sets those variables and overrides them from default.

**Comment by timglorioso** [comment]
Thanks @simonv3. For artist pages customization, it feels like nested theme will be a cleaner solution based on my understanding/imagining of those pages. I may need to handle that in the related PR to ensure the theme approach will work as I'm hoping.

**Comment by timglorioso** [comment]
Braindumping implications for themes with or without tokens

### Scenario
we have dark and light themes
they automatically toggle based on system setting
they manually toggle based on user site setting

we have a Button component, which has a few variants
**the Secondary variant changes based on whether we're in a dark or light theme**

#### With tokens

- the Secondary Button doesn't need to know anything about colors
- the Secondary Button doesn't need to know what theme we're in
- the theme needs to know about component internals

#### Without tokens

- the Secondary Button needs to know which colors to use
- the Secondary Button needs to know what theme we're in
- the theme needs to know about what theme we're in (so that components can then know)

**Comment by timglorioso** [comment]
Thinking we will want to use tokens, but keep Mirlo and Artist tokens separate... TBD. Is it possible with Typescript Emotion to have two different theme types feeding the same Provider instance? I guess if you make things optional?

<img width="822" alt="Themes" src="https://github.com/funmusicplace/mirlo/assets/8241942/086affd1-01e2-44f7-874f-d4c41f707ac6">

**Comment by simonv3** [comment]
@timglorioso Sorry if this is explained elsewhere but what are tokens?

**Comment by timglorioso** [comment]
A token is an applied scale value. Many tokens will be the same between Mirlo and Artist themes, but they lumping them together is a knot that we want to avoid. For example, Mirlo theme might have tokens for Button variants that don't map to anything meaningful in Artist theme (i.e. such Button variant isn't in the Artist design language).

```js

// color scales
const color = {

  // color scale
  gray: {
    ...,
    900: "#111111" // color scale value
  }
}

const darkTheme = {
  color: {
    ...,
    backgroundColor: color.gray[900] // token
    ...,
  }
}
```

**Comment by timglorioso** [comment]
Worth also mentioning that a design scale is a way of constraining options from near-infinite amount to at most a few dozen, to reduce decision fatigue and improve consistency.

**Comment by Cwpute** [comment]
i went ahead and addde the "help needed" tag since this issue hasn't seen activity in a good while. feel free to go ahead and remove the tag if it's unnecessary Tim !

**Comment by timglorioso** [comment]
Thanks @Cwpute, I think the Objective does a reasonable job of establishing context, but this one probably needs a bit more details to be ready to implement by contributors.

Details like: the Mirlo color scales. Which I think we have but maybe don't use consistently? Which TBH for me raises the question do we even care about this? The big picture here is trying get a grasp on visual branding and baking it into the code for easy usage.
