### ISSUE TITLE
Admin: Basic Admin

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#14]
* [ ] CRUD album details `3`
* [ ] CRUD track details `3`
* [ ] CRUD user details `3`

There is already some implementation of this in place, but it needs to be fleshed out.
