### ISSUE TITLE
API Tests

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#18]
* [x] Get tests running
* [ ] Write tests for basic endpoints
  * [ ] Artists
    * [x] id
    * [ ] id/subscribe (requires mocking stripe)
    * [x] feed
    * [x] index
    * [x] follow
    * [x] unfollow
  * [x] checkout (how do we write these tests?)
  * [x] posts
    * [x] id
    * [x] index
  * [x] trackgroups
    * [x] id
    * [x] id/download
    * [x] id/emailDownload
    * [x] id/purchase (requires mocking stripe)
    * [x] id/wishlist
    * [x] index
  * [ ] tracks
    * [ ] id
    * [ ] id/stream/segment
    * [ ] index
  * [ ] users
    * [ ]  userId
      * [ ] artists
        * [ ] index
        * [x] artistId
        * [ ] artistId/banner
          * [x] delete
          * [ ] create 
        * [ ] artistId/avatar
          * [x] delete
          * [ ] create
        * [x] artistId/subscriptionTiers
        * [x] artistId/subscriptionTiers/id
        * [ ] artistId/subscriptionTiers/download
        * [ ] artistId/supporters
        * [x] artistId/subscribers
      * [x] posts
        * [x] postId
        * [x] postId/publish
        * [x] index
      * [ ] subscriptions
        * [ ] subscriptionId
        * [ ] index
      * [ ] trackGroups
        * [x] index
        * [x] trackGroupId
        * [x] trackGroupId/cover
        * [ ] trackGroupId/publish
        * [x] trackGroupId/trackOrder
      * [ ] tracks
        * [ ] index
        * [ ] trackId/index
        * [ ] trackId/audio
      * [ ] feed
      * [ ] index
      * [x] purchases
    * [ ] index
* [x] Get tests running on github actions

**Comment by simonv3** [comment]
One thought for testing the stripe required endpoints is to text the exported function directly, not as a supertest, but rather as a function test. Then mock the stripe API to let it create the things we need. 

* [ ] trackgroup/id/purchase
* [ ] artist/id/subscribe

**Comment by georgkrause** [comment]
>  id/subscribe (requires mocking stripe)

Stripe provides a testing mode we could use for this: https://docs.stripe.com/test-mode?

**Comment by humancuration** [comment]
https://github.com/humancuration/mirlo/tree/main/test/new_tests

um, chatgpt 4o wrote these
